HInit -S mfccList -M model/hmm0 -H model/proto/hmm_DELUXE -l DELUXE -L data/train/ucup/ DELUXE
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_DENGAN -l DENGAN -L data/train/ucup/ DENGAN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_DUA -l DUA -L data/train/ucup/ DUA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_EMPAT -l EMPAT -L data/train/ucup/ EMPAT
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_HARI -l HARI -L data/train/ucup/ HARI
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_JUMAT -l JUMAT -L data/train/ucup/ JUMAT
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_KAMAR -l KAMAR -L data/train/ucup/ KAMAR
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_KAMIS -l KAMIS -L data/train/ucup/ KAMIS
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_MALAM -l MALAM -L data/train/ucup/ MALAM
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_MINGGU -l MINGGU -L data/train/ucup/ MINGGU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_ORANG -l ORANG -L data/train/ucup/ ORANG
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_PADA -l PADA -L data/train/ucup/ PADA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_PESAN -l PESAN -L data/train/ucup/ PESAN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_RABU -l RABU -L data/train/ucup/ RABU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SABTU -l SABTU -L data/train/ucup/ SABTU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SARAPAN -l SARAPAN -L data/train/ucup/ SARAPAN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SATU -l SATU -L data/train/ucup/ SATU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SAYA -l SAYA -L data/train/ucup/ SAYA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SELASA -l SELASA -L data/train/ucup/ SELASA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SENIN -l SENIN -L data/train/ucup/ SENIN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_STANDARD -l STANDARD -L data/train/ucup/ STANDARD
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SUITE -l SUITE -L data/train/ucup/ SUITE
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SUPERIOR -l SUPERIOR -L data/train/ucup/ SUPERIOR
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_TANPA -l TANPA -L data/train/ucup/ TANPA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_TIGA -l TIGA -L data/train/ucup/ TIGA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_UNTUK -l UNTUK -L data/train/ucup/ UNTUK