HInit -S mfccList -M model/hmm0 -H model/proto/hmm_DELUXE -l DELUXE -L data/labels/ DELUXE
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_DENGAN -l DENGAN -L data/labels/ DENGAN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_DUA -l DUA -L data/labels/ DUA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_EMPAT -l EMPAT -L data/labels/ EMPAT
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_HARI -l HARI -L data/labels/ HARI
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_JUMAT -l JUMAT -L data/labels/ JUMAT
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_KAMAR -l KAMAR -L data/labels/ KAMAR
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_KAMIS -l KAMIS -L data/labels/ KAMIS
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_MALAM -l MALAM -L data/labels/ MALAM
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_MINGGU -l MINGGU -L data/labels/ MINGGU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_ORANG -l ORANG -L data/labels/ ORANG
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_PADA -l PADA -L data/labels/ PADA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_PESAN -l PESAN -L data/labels/ PESAN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_RABU -l RABU -L data/labels/ RABU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SABTU -l SABTU -L data/labels/ SABTU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SARAPAN -l SARAPAN -L data/labels/ SARAPAN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SATU -l SATU -L data/labels/ SATU
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SAYA -l SAYA -L data/labels/ SAYA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SELASA -l SELASA -L data/labels/ SELASA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SENIN -l SENIN -L data/labels/ SENIN
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_STANDARD -l STANDARD -L data/labels/ STANDARD
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SUITE -l SUITE -L data/labels/ SUITE
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_SUPERIOR -l SUPERIOR -L data/labels/ SUPERIOR
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_TANPA -l TANPA -L data/labels/ TANPA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_TIGA -l TIGA -L data/labels/ TIGA
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_UNTUK -l UNTUK -L data/labels/ UNTUK
HInit -S mfccList -M model/hmm0 -H model/proto/hmm_sil -l sil -L data/labels/ sil